### ISSUE TITLE
Sileo causes reboot

### ISSUE THREAD

**Issue by saif6speed** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#10]
As the title says when opening sileo in a jailbroken state, my iPhone X on 16.5 immediately reboots. Panic log: https://drive.google.com/file/d/1_kEpYk2rkw3VtNqwc4-eUrDWWnpksyKt/view?usp=drivesdk

**Comment by yuvi-develop** [comment]
Do you see “dpkg interrupted” when you open sileo? Because i do and it’s not because of a tweak.

1 more thing, what do you see when you open a terminal? i see “====Session Ended====“.

**Comment by KpwnZ** [comment]
New version is available.
