### ISSUE TITLE
iphone x reboots 

### ISSUE THREAD

**Issue by Ssjb21** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#11]
when clicking start is just reboots the device

iPhone X
iOS 16.0.2

[panic-full-2023-12-28-081252.000.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/13787424/panic-full-2023-12-28-081252.000.txt)

**Comment by jthoward64** [comment]
May be related to #5, but the panic string looks different

**Comment by KpwnZ** [comment]
Please try the latest version v0.999.6.

**Comment by Ssjb21** [comment]
> Please try the latest version v0.999.6.

it works after 5 or 7 tries, but also after some mins the device reboots itself aka panic

**Comment by KpwnZ** [comment]
Fixed.

**Comment by KpwnZ** [comment]
> > Please try the latest version v0.999.6.
> 
> it works after 5 or 7 tries, but also after some mins the device reboots itself aka panic

Please open a new issue.
