### ISSUE TITLE
Does sideloading in a jailed state work?

### ISSUE THREAD

**Issue by yuvi-develop** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#15]
Does sideloading with an iOS like 16.5 and iphone X work(with altstore, e-sign, satella, etc.)?

**Comment by Haikal016** [comment]
See the readme,get a trollstore first

**Comment by yuvi-develop** [comment]
> See the readme,get a trollstore first

no where in the readme does it say and there’s no way to get trollstore without palera1n on kfd devices which means even if you run this tool after jailbreaking, the sep functionality would be useless.

**Comment by yuvi-develop** [comment]
> no where in the readme does it say 

nvm it does say it

**Comment by jthoward64** [comment]
Close as resolved?
