### ISSUE TITLE
iOS 16.2 iPhone 14 Pro: Not supported?

### ISSUE THREAD

**Issue by znexo** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#18]
![232C15D1-BBFF-4EC0-838F-0779C9CC50D3](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/155475413/e8df9869-f6b9-4270-952f-711c2c7eeaf7)
App crash about 5 seconds upon pressing start followed by a reboot. Device info in attachment.

**Comment by KpwnZ** [comment]
We do plan to add arm64e support.
