### ISSUE TITLE
"FATAL ERROR: failed to find offsets"

### ISSUE THREAD

**Issue by HiSaCC99** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#22]
I've got this error only using the latest pre-release (0.999.6). Other releases worked perfectly. 
Attached a photo of the error and other messages.

iPhone X, iOS 16.5.

![image](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/113647591/c04fbf60-51c8-4d13-a246-c3cc5b7685a2)

**Comment by KpwnZ** [comment]
New version is available: https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.7.
