### ISSUE TITLE
Randomly reboots after successfully jailbroken 

### ISSUE THREAD

**Issue by dejvi99** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#23]
I successfully jailbroke after couple of times clicking start button .
But after 10-15 minutes it randomly reboots 
Iphone x 16.3.1 

here is the panic log : 
![EDA759DA-BA29-49F8-8F86-B494EE594BF4](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/154866722/35165bb5-79a5-413f-935e-40a75d3d249a)
https://drive.google.com/file/d/1ewicX0jSi_jiSbc1hnrjRmMTRqEplvz4/view?usp=drivesdk

**Comment by juins1** [comment]
this happens to me too. Since like version .2

**Comment by michaelmelita1** [comment]
Pretty sure this is due to a broken ellekit installation.

Evelyn has stated that /var/jb/.installed_dopamine is required for proper installation of ellekit on semitethered jailbreaks.

**Comment by KpwnZ** [comment]
It seems that I managed to fix it. I will push a new update after some testing.

**Comment by KpwnZ** [comment]
New version is available.
