### ISSUE TITLE
Failed to load trustcache, no trustcache buffer provided

### ISSUE THREAD

**Issue by JojoZockt** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#24]
iPhone 8 on iOS 16.3.1 fails to jailbreak and panics. Reinstalling app and reseting iPhone didn't help. 

Image attached
![IMG_9724](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/56637738/7655d8af-957c-4ccf-a1ab-e037d5ebc8f9)

**Comment by KpwnZ** [comment]
Please install it with Trollstore.

**Comment by JojoZockt** [comment]
Very unstable, but works now. Thanks
