### ISSUE TITLE
reboots after jailbreak

### ISSUE THREAD

**Issue by Ssjb21** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#25]
device reboots after jailbreaking by 10 mins or so 
[Uploading panic-full-2024-01-08-153530.000.txt…]()

**Comment by KpwnZ** [comment]
New version is available.

**Comment by KpwnZ** [comment]
Please check https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.9.
