### ISSUE TITLE
Ellekit isnt installing correctly

### ISSUE THREAD

**Issue by michaelmelita1** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#26]
Hello. I've spoken to Evelyn about the crashing/reboots when ellekit is installed from Sileo. She informed me that /var/jb/.installed_dopamine is required for proper installation of ellekit on semitethered jailbreaks.

Having done this on my own install, it seems to install correctly (If not loading)

**Comment by KpwnZ** [comment]
Yeah I have tried that and it's still rebooting. Did you test it with this jailbreak?

**Comment by michaelmelita1** [comment]
I have indeed. iPhone X 16.5. It definitely helps, at least getting ellekit installed and avoiding the dpkg interrupted- crash loop

**Comment by KpwnZ** [comment]
Hmm, what's your ellekit version?

**Comment by michaelmelita1** [comment]
1.1

**Comment by KpwnZ** [comment]
I am testing with ellekit 1.0 now.

**Comment by michaelmelita1** [comment]
oh cool. well meowbrek2 is using 1.1 from https://ellekit.space. Might be worth adding that as a default source

have you gotten ellekit to successfully load tweaks?

**Comment by michaelmelita1** [comment]
Which commit? Tweaks still aren’t loading on 0.9999.7 even with the fix

**Comment by KpwnZ** [comment]
> Which commit? Tweaks still aren’t loading on 0.9999.7 even with the fix

The dyld dynamic patcher is broken on 0.999.7. Some previous versions I don't remember exactly has tweak injection already on iOS 16.5 iPhone X.

**Comment by michaelmelita1** [comment]
okay. ill check 0.9999.5 as .6 has the ofset issue. let me know if I can be of more assistance testing

**Comment by KpwnZ** [comment]
0.999.3 should be able to jailbreak iOS 16.5 iPhone X with system wide tweak injection. I just fixed the dyld patcher and new version will be uploaded later.

**Comment by michaelmelita1** [comment]
Yep, works a charm in springboard tweaks. In app tweaks don’t work for some reason. But it’s good enough for me to test my tweaks for the time being. Cheers

**Comment by michaelmelita1** [comment]
Okay so after some tests on 0.999.3, it seems stable unless 2 conditions happen.

1: Crashing due to high memory usage
2: Crashing when the screen is turned off (Deepsleep)?

**Comment by KpwnZ** [comment]
> Okay so after some tests on 0.999.3, it seems stable unless 2 conditions happen.
> 
> 
> 
> 1: Crashing due to high memory usage
> 
> 2: Crashing when the screen is turned off (Deepsleep)?

Wow valuable information!

**Comment by KpwnZ** [comment]
New version is available.
