### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ilovecatsquiet** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#27]
Recently tried installing this jailbreak on my iphone 8 ios 16.5. It seemed to install fine on my first try, but when I tried to install packages in sileo, they just didn’t install at all. Another thing is that when I rebooted, I wasn’t able to jailbreak again, my device would just keep rebooting without actually doing anything. Also all the icons are not showing.
![IMG_0242](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/156492106/f08d3c1f-5457-4df2-a3cf-01bc5b91ab3a)

**Comment by KpwnZ** [comment]
0.999.7 breaks the previous dyld patcher. You can revert it back and compile it from source code.
