### ISSUE TITLE
Iphone 8 plus ios 16.6.1 issue.

### ISSUE THREAD

**Issue by Pwn0day** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#29]
i used the latest ipa, the app keep crashing then it reboots after many times of trying.

**Comment by KpwnZ** [comment]
Got it. Work in progress now.

**Comment by Pwn0day** [comment]
Thank @KpwnZ for your interest. You are the most active developers I have ever seen.

**Comment by Pwn0day** [comment]
@KpwnZ did you fix it ?

**Comment by Pwn0day** [comment]
@KpwnZ Re you going to push an update ?

**Comment by KpwnZ** [comment]
You can fix it by yourself if you need that now since everything is completely open source.

**Comment by Pwn0day** [comment]
@KpwnZ waiting you

**Comment by KpwnZ** [comment]
> @KpwnZ waiting you 

Don't wait. I believe you are much more skillful.

**Comment by Pwn0day** [comment]
@KpwnZ i said i don't have any mac now to compile it i'm travelling everyday, i will reach home after one month ? even if i have skills, i don't have the time + my mac ? thanks !

**Comment by KpwnZ** [comment]
New version is available.

**Comment by Pwn0day** [comment]
> New version is available.

i tried it but it keeps restarting

**Comment by Pwn0day** [comment]
https://www.filemail.com/d/truwwfvrxgsjpnd 
this the panic file

**Comment by Pwn0day** [comment]
the app still crashing @KpwnZ

**Comment by Pwn0day** [comment]
> New version is available.

i have 8 plus with ios 16.6.1  @KpwnZ
