### ISSUE TITLE
Workaround for "deep sleep" and "session ended" bugs

### ISSUE THREAD

**Issue by HiSaCC99** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#32]
USE AT YOUR OWN RISK!
I am not responsible for any damage done to your phone.

DISCLAIMER:
I'm aware that IT IS NOT the best/proper solution for fixing those bugs (specially the "session ended" bug, because there is a thread on Dopamine GitHub that explain this workaround make this error 10 time worse. Opa words!), so wait the developer to fix these, please!

Hi y'all! I was able to get past the "deep sleep" bug installing Fiona (julioverne repo) and "session ended" bug installing login (https://nt994.github.io/ repo). 
Fiona doesn't allow to enter in "deep sleep" the iPhone because it keeps Wi-Fi always connected when the iPhone is locked (I noticed a slightly battery drain), while the other package is able to get past to some error to use the terminal (you can't use "su" and "sudo" command). My iPhone didn't reboot for over 6 hours and counting!

PS: @KpwnZ if you think I should close/remove this post, please tell me! Thank you for your hard work as always!

**Comment by KpwnZ** [comment]
New version is available now. https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.10. Deep sleep panic should be fixed.

**Comment by HiSaCC99** [comment]
> New version is available now. https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.10. Deep sleep panic should be fixed.

Yep! Deep Sleep panic resolved! Thank you for continuing working on this project!

**Comment by KpwnZ** [comment]
For the "Session Ended" bug, I have already known the reason but I am a little bit busy with my own research now (and too lazy to fix). If there can be other developers who are interested in it feel free to open a PR or contact me if you need any help.

**Comment by jthoward64** [comment]
> session

For the momment I fixed 'session ended' in NewTerm 3 with `login` from Thành Nguyễn's [repo](https://nt994.github.io/) to get NewTerm 3 to work

**Comment by jthoward64** [comment]
> For the "Session Ended" bug, I have already found the reason but I am a little bit busy with my own research now (and too lazy to fix). If there can be other developers who are interested in it feel free to open a PR or contact me if you need any help.

If you don't mind posting what you know about it I'd love to take a crack at it (I've been wanted to help out with this project but I've been unsure where to start)

**Comment by KpwnZ** [comment]
> > For the "Session Ended" bug, I have already found the reason but I am a little bit busy with my own research now (and too lazy to fix). If there can be other developers who are interested in it feel free to open a PR or contact me if you need any help.
> 
> If you don't mind posting what you know about it I'd love to take a crack at it (I've been wanting to help out with this project but I've been unsure where to start)

There is a todo in jailbreakd https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/blob/0e208992c4621c585932714e6de1f5e417f0d8b4/basebin/jailbreakd/main.mm#L316

**Comment by jthoward64** [comment]
> > > For the "Session Ended" bug, I have already found the reason but I am a little bit busy with my own research now (and too lazy to fix). If there can be other developers who are interested in it feel free to open a PR or contact me if you need any help.
> > 
> > 
> > If you don't mind posting what you know about it I'd love to take a crack at it (I've been wanting to help out with this project but I've been unsure where to start)
> 
> There is a todo in jailbreakd
> 
> https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/blob/0e208992c4621c585932714e6de1f5e417f0d8b4/basebin/jailbreakd/main.mm#L316

I'm having some trouble building the code in basebin, I extracted the deb.tar, binaries.tar, and ramdisk.dmg files from the ipa and extracted deb and binaries to the root folder but I'm getting these two errors depending on the folder I try to build:

```log
clang -framework Foundation -framework CoreServices -framework Security -I../_shared -I./src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -arch arm64 -miphoneos-version-min=15.0 -fobjc-arc  -o jbctl src/jailbreakd.m src/main.m
codesign -f -s - --timestamp=none --all-architectures --entitlements ./entitlements.plist --deep src/jailbreakd.m
mv jbctl ../../binaries
rm ../../binaries/jb.tc
rm: ../../binaries/jb.tc: No such file or directory
make: *** [jbctl] Error 1
```

```log
clang -framework Foundation -framework CoreServices -framework Security -framework IOKit -I./src/_shared -I./src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -arch arm64 -miphoneos-version-min=15.0 -fobjc-arc -O2 -dynamiclib -rpath @loader_path/fallback  -L./src/_shared -lbsm -lellekit -o launchdhook.dylib src/boot_info.m src/common.m src/daemon_hook.m src/envbuf.m src/ipc_hook.m src/jailbreakd.m src/main.m src/spawn_hook.m
ld: tapi error: malformed file
/Users/tagho/Source/Def1nit3lyN0tAJa1lbr3akTool/basebin/_shared/libellekit.tbd:3:26: error: unknown platform
targets:               [ arm64, arm64e ]
                         ^~~~~
 in '/Users/tagho/Source/Def1nit3lyN0tAJa1lbr3akTool/basebin/_shared/libellekit.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [launchdhook.dylib] Error 1
```

Is there something I'm missing, or am I just using the wrong compiler/command?

**Comment by KpwnZ** [comment]
> > > > For the "Session Ended" bug, I have already found the reason but I am a little bit busy with my own research now (and too lazy to fix). If there can be other developers who are interested in it feel free to open a PR or contact me if you need any help.
> > > 
> > > 
> > > If you don't mind posting what you know about it I'd love to take a crack at it (I've been wanting to help out with this project but I've been unsure where to start)
> > 
> > 
> > There is a todo in jailbreakd
> > https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/blob/0e208992c4621c585932714e6de1f5e417f0d8b4/basebin/jailbreakd/main.mm#L316
> 
> I'm having some trouble building the code in basebin, I extracted the deb.tar, binaries.tar, and ramdisk.dmg files from the ipa and extracted deb and binaries to the root folder but I'm getting these two errors depending on the folder I try to build:
> 
> ```
> clang -framework Foundation -framework CoreServices -framework Security -I../_shared -I./src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -arch arm64 -miphoneos-version-min=15.0 -fobjc-arc  -o jbctl src/jailbreakd.m src/main.m
> codesign -f -s - --timestamp=none --all-architectures --entitlements ./entitlements.plist --deep src/jailbreakd.m
> mv jbctl ../../binaries
> rm ../../binaries/jb.tc
> rm: ../../binaries/jb.tc: No such file or directory
> make: *** [jbctl] Error 1
> ```
> 
> ```
> clang -framework Foundation -framework CoreServices -framework Security -framework IOKit -I./src/_shared -I./src -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -arch arm64 -miphoneos-version-min=15.0 -fobjc-arc -O2 -dynamiclib -rpath @loader_path/fallback  -L./src/_shared -lbsm -lellekit -o launchdhook.dylib src/boot_info.m src/common.m src/daemon_hook.m src/envbuf.m src/ipc_hook.m src/jailbreakd.m src/main.m src/spawn_hook.m
> ld: tapi error: malformed file
> /Users/tagho/Source/Def1nit3lyN0tAJa1lbr3akTool/basebin/_shared/libellekit.tbd:3:26: error: unknown platform
> targets:               [ arm64, arm64e ]
>                          ^~~~~
>  in '/Users/tagho/Source/Def1nit3lyN0tAJa1lbr3akTool/basebin/_shared/libellekit.tbd'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [launchdhook.dylib] Error 1
> ```
> 
> Is there something I'm missing, or am I just using the wrong compiler/command?

You don't need to compile `jbctl` now. It's out of date.

**Comment by jthoward64** [comment]
> You don't need to compile `jbctl` now. It's out of date.

It's not just jbctl, I can't compile any of the makefiles; but if you're not familiar with the issue I can mess around with it and see if I can get it working. Thanks!

**Comment by KpwnZ** [comment]
> > You don't need to compile `jbctl` now. It's out of date.
> 
> It's not just jbctl, I can't compile any of the makefiles; but if you're not familiar with the issue I can mess around with it and see if I can get it working. Thanks!

idk if this can be related to the SDK version. Haven't encounter this previously.

**Comment by nyathea** [comment]
You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.

Use with caution as this runs without a password unlike sudo.

https://github.com/BomberFish/pseudo/releases/tag/v1.0.0

Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.

**Comment by Su4o** [comment]
> You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> 
> Use with caution as this runs without a password unlike sudo.
> 
> https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> 
> Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.

 I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!

**Comment by jthoward64** [comment]
> > You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> 
> > 
> 
> > Use with caution as this runs without a password unlike sudo.
> 
> > 
> 
> > https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> 
> > 
> 
> > Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.
> 
> 
> 
>  I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!
> 
> 
> 
> (_sorry for the dumb question…_)

Click the i button, change mobile to root and change owner group and other to have execute enabled

**Comment by Su4o** [comment]
> > > You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> > 
> > 
> > > 
> > 
> > 
> > > Use with caution as this runs without a password unlike sudo.
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> > 
> > 
> > > 
> > 
> > 
> > > Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.
> > 
> > 
> > I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!
> > (_sorry for the dumb question…_)
> 
> Click the i button, change mobile to root and change owner group and other to have execute enabled

Wait, I can't move it in anymore?? i get the following error on filza "Error The operation couldn't be completed. Permission denied"

**Comment by nyathea** [comment]
> > > > You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Use with caution as this runs without a password unlike sudo.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.
> 
> > > 
> 
> > > 
> 
> > > I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!
> 
> > > (_sorry for the dumb question…_)
> 
> > 
> 
> > Click the i button, change mobile to root and change owner group and other to have execute enabled
> 
> 
> 
> Wait, I can't move it in anymore?? i get the following error on filza "Error The operation couldn't be completed. Permission denied"
> 
> 

Try using the trollstore version of filza. And make sure you're putting it in the /var/jb/usr/bin directory.

**Comment by Su4o** [comment]
> > > > > You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Use with caution as this runs without a password unlike sudo.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!
> > 
> > 
> > > > (_sorry for the dumb question…_)
> > 
> > 
> > > 
> > 
> > 
> > > Click the i button, change mobile to root and change owner group and other to have execute enabled
> > 
> > 
> > Wait, I can't move it in anymore?? i get the following error on filza "Error The operation couldn't be completed. Permission denied"
> 
> Try using the trollstore version of filza. And make sure you're putting it in the /var/jb/usr/bin directory.

Tried it, still doesn’t work. It gives me the same error. I’ve done the Trollstore ver instead too.

**Comment by KpwnZ** [comment]
If anyone is still interested in fixing the setuid problem, you need to update the `struct ucred` in `struct proc_ro`.

**Comment by KpwnZ** [comment]
> > > > > > You can use “pseudo” as an alternative for now. It’ll work like sudo and give you root privileges in newterm.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Use with caution as this runs without a password unlike sudo.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > https://github.com/BomberFish/pseudo/releases/tag/v1.0.0
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Download the file and put it in /var/jb/usr/bin using filza and change the permissions of it to root:wheel and make it executable.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > I moved it but don’t know how to change perms to root:wheel? Can you give the step by step solution or a small video? Thanks!
> > > 
> > > 
> > > > > (_sorry for the dumb question…_)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Click the i button, change mobile to root and change owner group and other to have execute enabled
> > > 
> > > 
> > > Wait, I can't move it in anymore?? i get the following error on filza "Error The operation couldn't be completed. Permission denied"
> > 
> > 
> > Try using the trollstore version of filza. And make sure you're putting it in the /var/jb/usr/bin directory.
> 
> Tried it, still doesn’t work. It gives me the same error. I’ve done the Trollstore ver instead too.

It's fixed now, update will be released later.

**Comment by jthoward64** [comment]
> It's fixed now, update will be released later.

Awesome! Thank you so much, I tried to figure out a PR but got lost in the weeds of iOS

**Comment by KpwnZ** [comment]
v1.0.1 should fix all of bugs mentioned here.

**Comment by Su4o** [comment]
> v1.0.1 should fix all of bugs mentioned here.

yessirr, thanks @KpwnZ

**Comment by jthoward64** [comment]
Worth noting that it didn't work for me at first but after reinstalling system-cmds and sudo, re-jailbreaking, and reinstalling system-cmds and sudo again I got a prompt in newterm. The reason is probably that even though the setuid syscall works now, the original binaries didn't have the setuid bit and had to be reinstalled to set it.
