### ISSUE TITLE
Device reboots after turned off for a few minutes.

### ISSUE THREAD

**Issue by ilovecatsquiet** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#34]
Hello my friend, I have been using the new version of the jailbreak 0.999.9 and it has been going perfectly apart from one issue. Whenever I turn off my device, I have noticed that it will reboot after a few minutes and get rid of the jailbreak. I hope you can look into this issue and fix it in a release soon because I really love the jailbreak so far. I also just want to say thank you for everything you’ve done so far and making jailbreaking possible on my old device. ❤️ iPhone 8 iOS 16.5

**Comment by KpwnZ** [comment]
https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/issues/33

**Comment by KpwnZ** [comment]
I will close this issue since it's duplicate.

**Comment by KpwnZ** [comment]
New version is available now. https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/releases/tag/v0.999.10.
