### ISSUE TITLE
0.999.10 Instant Reboot after pressing start

### ISSUE THREAD

**Issue by roc4et** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#35]
Hey, my iPhone X on iOS 16.1.2, instantly reboots when clicking on start.
https://drive.google.com/file/d/1yxaRoosx4H5DvOsk_4Ld6od5U01b8Ju1/view?usp=share_link

**Comment by imrobbyrc** [comment]
Duplicate with #3

**Comment by roc4et** [comment]
> Duplicate with #3

There still is no fix though, I have waited a few minutes and it all happens the same

**Comment by imrobbyrc** [comment]
Still no fix, just wait for the dev to fix it, or you can try build v7

**Comment by KpwnZ** [comment]
Very weird, it seems like every other version works perfectly now...

**Comment by imrobbyrc** [comment]
Just testing with kfd other projects mikasa and PureKFD, it's seem problem with puaf method, i try other than landa it crash or panics like this. But with landa method seems working along with 512 puaf pages

**Comment by KpwnZ** [comment]
> Just testing with kfd other projects mikasa and PureKFD, it's seem problem with puaf method, i try other than landa it crash or panics like this. But with landa method seems working along with 512 puaf pages

Can you set a breakpoint before entering the cleanup routine?

**Comment by imrobbyrc** [comment]
I use latest ipa from both projects, will try tomorrow to build those projects with my machine

**Comment by KpwnZ** [comment]
I will push a workaround today.

**Comment by KpwnZ** [comment]
v0.999.11 is available.

**Comment by Dansco** [comment]
https://drive.google.com/file/d/1S2Gg_W7av0R7JLrvYE8yp8ARB3I4D3cr/view?usp=drivesdk

iPhone X iOS 16.1.2 using v0.999.11

**Comment by KpwnZ** [comment]
Now it should support iOS 16.1.X.
