### ISSUE TITLE
webkit not working.

### ISSUE THREAD

**Issue by libr2** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#36]
as the title says.

https://drive.google.com/file/d/1EB_hrhsD80x9yXMbIhvrqH73siA6Y100/view?usp=drivesdk

https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/157130969/3af88d36-8461-4768-a9b5-19e9455fd553

**Comment by HiSaCC99** [comment]
If I remember correctly @KpwnZ said that he is aware of this bug on a Reddit post/comment and he is working on it

**Comment by jthoward64** [comment]
Yeah I've had the same issue (iPhone 8 Plus 16.4.0)

**Comment by Bubblemint864** [comment]
For me it doesn't work most of the time but sometimes it works, iPhone X 16.0

**Comment by Pwn0day** [comment]
Fixing soon.

**Comment by Pwn0day** [comment]
Mark as completed @KpwnZ

**Comment by KpwnZ** [comment]
Fixed in the latest version.
