### ISSUE TITLE
0.999.11 App crashing issue with iphone 8 plus ios 16.6.1

### ISSUE THREAD

**Issue by Pwn0day** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#38]
When i press start i wait for less than a minute then the app crash, when i press again the phone reboot.

**Comment by nyathea** [comment]
Same, iPhone X 16.6

**Comment by OdymarGamer** [comment]
same

**Comment by Pwn0day** [comment]
> Same, iPhone X 16.6

please join us on the discord
https://discord.gg/23PqE4Jd

**Comment by Pwn0day** [comment]
> same

please join us on the discord
https://discord.gg/23PqE4Jd

**Comment by Pwn0day** [comment]
mark as complete @KpwnZ
