### ISSUE TITLE
iPhone X iOS 16.6 reboot device

### ISSUE THREAD

**Issue by murkwhite** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#39]
I will add crash log, maybe you can fix it 
[panic-full-2024-01-22-055334.000.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14004626/panic-full-2024-01-22-055334.000.zip)

**Comment by Pwn0day** [comment]
Completed @KpwnZ

**Comment by Pwn0day** [comment]
Completed @KpwnZ

**Comment by KpwnZ** [comment]
Fixed in the latest version.
