### ISSUE TITLE
0.999.11 iPhone X iOS 16.1.2

### ISSUE THREAD

**Issue by roc4et** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#40]
When pressing start, the app just freezes. Waiting doesn’t do anything and exiting and trying again just reboots the device.

**Comment by Bubblemint864** [comment]
As silly as it may sound, have you guys tried to jailbreak multiple times? Seems to work for me after a few attempts. If that doesn't work, reinstalling the IPA and trying again works.

**Comment by KpwnZ** [comment]
Yeah it’s a known issue.

**Comment by Pwn0day** [comment]
> Yeah it’s a known issue.

so there is a fix i tried many times

**Comment by ansnw** [comment]
iPhone 8+ 16.1 having the same issue, all the past releases didn’t work either

**Comment by KpwnZ** [comment]
We got a support channel now. https://discord.gg/23PqE4Jd

**Comment by KpwnZ** [comment]
Now it should support iOS 16.1.X.
