### ISSUE TITLE
iOS 16.6b1?

### ISSUE THREAD

**Issue by SpinnySpiwal** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#42]
ios 16.6b1 uses the 16.5 kernel, so i imagine it would work.

**Comment by SlimShadys** [comment]
I tried with 16.6 Beta 1 on iPhone X, but when pressing Start the app freezes and crashes. Trying multiple times doesn't solve anything, still crashes. No reboots though.

**Comment by OdymarGamer** [comment]
> I tried with 16.6 Beta 1 on iPhone X, but when pressing Start the app freezes and crashes. Trying multiple times doesn't solve anything, still crashes. No reboots though.

same

**Comment by KpwnZ** [comment]
Close as duplicate.
