### ISSUE TITLE
sideloaded/trollstore app doesn't works

### ISSUE THREAD

**Issue by likertuban** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#43]
iPhone X iOS 16.3.1
hello, it seems that after jailbreaking with Def1nit3lyN0tAJa1lbr3akTool has caused all of my sideloaded app including app installed using trollstore to crash/not opening, even if I installed appsync unify, the app still won't open, app installed from trollstore need to be reinstalled, I think this is related to re/sign problem, I want to try ldid, but I can't use newterm beta 3, so I can't use ldid, Filza tweak version doesn't open either, but Filza trollstore do works, can't run ldid tho', any solution?
I had some app that I develop using xamarin for works before and the ipa has been long gone, so the currently installed is the only one left, this is the utmost important one for me, please help :-(

**Comment by Bubblemint864** [comment]
Reinstalling the apps through Trollstore usually fixes it for me, have you tried that? (You don't need to delete the app and all data should be retained but if you're unsure test it on an app that isn't too important)

Also make sure you have replaced one of your apps to be used as the persistence helper.

**Comment by likertuban** [comment]
> Reinstalling the apps through Trollstore usually fixes it for me, have you tried that? (You don't need to delete the app and all data should be retained but if you're unsure test it on an app that isn't too important)
> 
> Also make sure you have replaced one of your apps to be used as the persistence helper.

it works for app that is installed from trollstore before, but the app for my works is something I've sideload using visual studio and I no longer had any ipa for it

**Comment by Bubblemint864** [comment]
You should be able to save the IPA with a tool like BFDecrypt I think, I'm not so well informed on this topic so I may be wrong - but I'm very certain it's possible.

**Comment by likertuban** [comment]
> You should be able to save the IPA with a tool like BFDecrypt I think, I'm not so well informed on this topic so I may be wrong - but I'm very certain it's possible.

okay fixed, turned out I just need to take the bunde.app folder and make Payload folder then zip it, since it's not from appstore, it doesn't need to be decrypted, or perhaps because it's on my own iPhone?
well, for now I revert back to palera1n until at least filza tweak (not trollstore version), newterm 3, appsync unify and webkit work before using this jailbreak tool, until then everyone, I hope this jb become more stable as soon as possible, so I could use it, doesn't have native SEP is a bit frustrating after all
