### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by jthoward64** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#46]
I'm no graphic designer, but I threw together a quick little icon in Inkscape that I'll probably add to my theme on my phone that might be good fit at least as a placeholder.

SVG:
![NotAJailbreakIcon](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/29828269/b25326d3-473d-4336-ae1e-6146e998af5c)

PNG:
![NotAJailbreakIcon](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/29828269/b76bcf3b-2c29-4cec-b17a-ad5fe4dbebeb)

**Comment by ilovecatsquiet** [comment]
Like it, good temporary fix for the app icon since it’s just blank right now 🙂

**Comment by Bubblemint864** [comment]
I'm gonna be honest it doesn't give off the vibes of an iOS app icon - and the current icon matches the nature of the name soooooooo 🦆

**Comment by jthoward64** [comment]
> I'm gonna be honest it doesn't give off the vibes of an iOS app icon - and the current icon (or rather the lack of an icon) matches the nature of the name soooooooo 🦆

Actually that kinda makes sense lol
