### ISSUE TITLE
Device Restarts After Jailbreaking Again

### ISSUE THREAD

**Issue by TheLameGod** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#47]
recently i restarted ny phone because of lag like after 5 minutes of jailbreaking and now when i try to re-jailbreak, it just restarts (kernel panic afaik?) and it just keeps on restarting over and over again.

**Comment by KpwnZ** [comment]
Update to the latest version/attach the panic log/wait a few minutes after booting before retry.
