### ISSUE TITLE
panics

### ISSUE THREAD

**Issue by libr2** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#49]
unfortunately, the new versions didn't fix it (**at least not for me**) my device still panics randomly multiple times throughout the day.
crash log:
https://drive.google.com/file/d/1KjjVS5VA7LfMlozA5Hr2DHHY11oZ58lg/view?usp=drivesdk
and thank u again for creating this project!

**Comment by KpwnZ** [comment]
These are different reasons.

**Comment by libr2** [comment]
> These are different reasons.

is it bcus of the tweaks i have or?

**Comment by KpwnZ** [comment]
> > These are different reasons.
> 
> is it bcus of the tweaks i have or?

I don't know for now. But I haven't received other similar reports.
