### ISSUE TITLE
Still messing up for me, issue:

### ISSUE THREAD

**Issue by xoxo2024** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#53]
![IMG_7740](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/157663884/feeb38d0-4bfc-4828-9f0f-952287ff7dfa)

**Comment by KpwnZ** [comment]
Read the README carefully before installing. You need to use Trollstore to install the IPA.
