### ISSUE TITLE
After using it for a period of time all applications on the phone cannot be accessed

### ISSUE THREAD

**Issue by Tikofu** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#54]
After jailbreaking on iPhone X 16.4.1, after a period of time, it appears that no application can be accessed, and even the phone's settings menu cannot be accessed. The only solution is to forcibly restart the phone. What is the reason for this? Have you ever encountered this problem?

**Comment by KpwnZ** [comment]
This should be related to your tweaks which are not fully compatible with iOS 16.
