### ISSUE TITLE
NewTerm3 Session Ended ; SSH working via user mobile, can not change password

### ISSUE THREAD

**Issue by phillipgoik** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#55]
iPhone 8 Plus A11, iOS 16.5
When I open NewTerm3 its immediately shows "Session Ended". 
I´ve tried reinstalling "system-cmds" and "shell-cmds". I´ve checked the rights for /private/preboot/<UUID>. For me its root:whell, 0755. That should be fine. 

Viel SSH I can login via user mobile. But I´m unable to change the password. 

Do you have any suggestions please? :-)
![20240125](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/79841144/4aa91e0b-aff0-4896-be9d-d2f751274188)
![20240125_2](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/79841144/3f9a0260-ca1a-4752-9d9a-eab430a26330)

**Comment by jthoward64** [comment]
#32
