### ISSUE TITLE
Kernel Panic on iPhone X (iOS 16.2)

### ISSUE THREAD

**Issue by HorrorTroll** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#59]
Kernel Panic happen after press Start button, tested on 1.0.0b

Panic log:
[panic-full-2024-01-26-191030.0002.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14065517/panic-full-2024-01-26-191030.0002.txt)

**Comment by KpwnZ** [comment]
Please just retry

**Comment by HorrorTroll** [comment]
> Please just retry

I've did retry like more than 30 times and still panic. No dice

**Comment by KpwnZ** [comment]
OK it will be fixed in next version.

**Comment by KpwnZ** [comment]
Fixed in the latest version.

**Comment by HorrorTroll** [comment]
It work now, thanks.
![2793AA4F-B859-4F18-9F59-CB61A1F8E94A](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/24840279/9e4d440c-8d08-4c6a-bf25-b43d9ce6141f)
