### ISSUE TITLE
Support for Icleaner

### ISSUE THREAD

**Issue by zraf0** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#60]
Icleaner seem to be always crash
I install from The official repo and it cant install it.
I use other repo and it work but always crash
I doubt that this is because of the jailbreak tool cus when i install icleaner with palera1n jailbreak it work normally, and I haven’t updated my software version since that if you wonder.

**Comment by KpwnZ** [comment]
work in progress

**Comment by libr2** [comment]
yeah same here even the limneos tweaks such as bioprotect, audiochanger and the rest of them send me straight to safe mode.

**Comment by KpwnZ** [comment]
Well for iCleaner I guess it doesn't support iOS 16 for now.

**Comment by KpwnZ** [comment]
v1.0.1 should fix that.
