### ISSUE TITLE
Can't access files with filza 

### ISSUE THREAD

**Issue by maansial** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#63]
Can't access files with filza only all empty folders

**Comment by jthoward64** [comment]
Make sure you are using an iOS 16 compatible version of Filza. Don't use any version of Filza you get from Sileo, instead use the Trollstore-compatible version.

**Comment by Su4o** [comment]
I'm still having the same problem @jthoward64

**Comment by jthoward64** [comment]
> I'm still having the same problem @jthoward64

What version of Filza (NOT FilzaEscaped) are you running?

**Comment by Su4o** [comment]
filza ipa from r/jailbreak. If you can provide the link to the filza you mentioned, I'll download that instead.

**Comment by bewl87** [comment]
https://tigisoftware.com/download/Filza_NoURLScheme_4.0.0.ipa

**Comment by maansial** [comment]
> https://tigisoftware.com/download/Filza_NoURLScheme_4.0.0.ipa
[<3]
Thanks brother, install with trollstore, work like charm
