### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by pwkdje** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#67]
After restarting, it seems like I can't jailbreak

**Comment by KpwnZ** [comment]
Can not reproduce.

**Comment by pwkdje** [comment]
After restarting, Is there any way again Jailbreak

**Comment by KpwnZ** [comment]
I don't know what you have encountered. Any logs? Otherwise we are not able to reproduce your issue and we cannot do anything.
