### ISSUE TITLE
Is this legit?

### ISSUE THREAD

**Issue by TheGithubJoshua** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#7]
Is this legit or is it just some Fugu100ProMaxUltra type thing?

**Comment by aBanjo12** [comment]
It's real but I don't think it supports many phones/versions

**Comment by KpwnZ** [comment]
Def1nit3lyN0tAJa1lbr3akToolI5aJ4iLbr3aKTo0LButCurr3ntLy0NlyTe5ted0nS3veRaLv3rs1on.

**Comment by jthoward64** [comment]
Definitely Not A Jailbreak Tool Is a JaiLbreaK TooL But Currently only Tested on SeveraL(?) version

**Comment by gamer191** [comment]
It's legit according to https://ios.cfw.guide/installing-notajb/. Ios.cfw.guide is a legit site

**Comment by TheGithubJoshua** [comment]
Thanks!
