### ISSUE TITLE
[IPAD 6GEN | IOS 16.1] (1.0.0 VER) Jailbreaks, but then reboots instantly.

### ISSUE THREAD

**Issue by Su4o** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#70]
I have updated Def1nit3lyN0tAJa1lbr3akTool](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool to 1.0.0 and tried jailbreaking my ipad. Here's what happened.

First try of jailbreaking, rebooted
second try of jailbreaking, worked but rebooted again

So, I went to the analytics & improvements section on settings and I've been noticed these

panic-full.ips (2023-11-29 --> 2024-01-30) (a lot of times) (for ver 1.0.0 and lower)
JetsameEvent.ips (2023-11-16 --> 2024-01-13) (a lot of times) (for ver 1.0.0 and lower)

The jailbreak did work before at late 2023 to early 2024 (lower than ver 1.0.0), but now it just reboots. (now ver 1.0.0) 
sadly won't let me copy and of the .ips files though

**Comment by jthoward64** [comment]
.ips files are just JSON, can you just rename the file to .txt or .json and upload it here?

**Comment by Su4o** [comment]
Nevermind, seems like it solved if i tried it again. Seems weird that I'm getting panic kernals, but ill be fine for now.
