### ISSUE TITLE
All Apps are 'frozen'

### ISSUE THREAD

**Issue by BakaGzRay12456** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#72]
iPhoneX 16.5
Sometimes my apps will look like 'frozen',and I can't run any app in my iPhone!
I must force restart my iPhone then re-jailbreak when they were 'frozen'

**Comment by BakaGzRay12456** [comment]
oh ,It freeze on just now.

**Comment by KpwnZ** [comment]
This might be related to some tweaks.
