### ISSUE TITLE
jailbreak

### ISSUE THREAD

**Issue by pwkdje** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#73]
![487EB9FEF228C470CD3CFA5A5A28D8ED](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/103505111/7cf5eef3-78bc-450d-b950-219c85d9c4d4)
Why is  jailbreak stuck here all the time

**Comment by pwkdje** [comment]
iPhone8 ios16.6

**Comment by jthoward64** [comment]
Can you copy/paste that log here? Also, if you look in settings->privacy->analytics->data do you see any crash reports or panics?

**Comment by pwkdje** [comment]
[panic-full-2024-02-01-110433.000.ips.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14119951/panic-full-2024-02-01-110433.000.ips.zip)
是不是这个文件

**Comment by KpwnZ** [comment]
We have noticed the problem and are working on a fix.

**Comment by pwkdje** [comment]
[jailbreakd-2024-02-01-144754.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14121356/jailbreakd-2024-02-01-144754.zip)

**Comment by KpwnZ** [comment]
v1.0.1 should fix this bug.
