### ISSUE TITLE
iPhone 11 (16.2)

### ISSUE THREAD

**Issue by vrnsoma** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#75]
I’m not sure what’s going wrong but I’ve installed via TrollStore and when I run the app this is what shows up.

![8BE996B6-14C0-40EA-89FF-EC264D01EF03](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/6080203/ebfec608-507e-4711-984e-8a2ac0a7bf27)

 I did try  Cluckabunga . the passcode faces requires open kernel.  When I do open the kernel it just freezes the app. The other springboard mods work without “opening” the kernel. I’m not sure if there’s something wrong since both aren’t working.

 I’m not knowledgeable enough to spot the issue. I’ve attached the logs below. 
 
[ANECompilerService.cpu_resource-2024-02-02-184356.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14150079/ANECompilerService.cpu_resource-2024-02-02-184356.zip)

The process gets stuck at # 15 EVERYTIME I try even after reboot. I’m tempted to try a reset but I don’t want to have to go through the pain of setup.

**Comment by libr2** [comment]
this is an arm64 jailbreak, ur phone is not supported yet.

**Comment by jthoward64** [comment]
Check out https://github.com/mineek/Serotonin in the meantime

**Comment by jthoward64** [comment]
@vrnsoma maybe close this issue if there's nothing else?
