### ISSUE TITLE
theos make project problem

### ISSUE THREAD

**Issue by pwkdje** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#76]
I installed Theos and it may automatically restart during the make project process
[panic-full-2024-02-03-162648.000.ips.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14150751/panic-full-2024-02-03-162648.000.ips.zip)

**Comment by KpwnZ** [comment]
Please try updating to v1.0.1.
