### ISSUE TITLE
[Reboot Problem] Random reboots out of nowhere.

### ISSUE THREAD

**Issue by Su4o** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#77]
I was using [Serotonin](https://github.com/mineek/Serotonin) to jailbreak my iPad, but didn’t liked it cause of to many procedures, battery drain problems, etc.) so I switched back to DNAJB (defentlynotajailbreak) and I successfully jailbroke my iPad 6gen (iOS 16.1), but after downloading powercuff, resprining, after ~5 seconds it rebooted my iPad and un-jb’d me. Here are some file logs I got. 
[JetsamEvent-2024-02-03-072036.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151505/JetsamEvent-2024-02-03-072036.txt)
[SystemMemoryReset-2024-02-03-072939.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151506/SystemMemoryReset-2024-02-03-072939.txt)
[ExcUserFault_xpcproxy-2024-02-03-073430.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151507/ExcUserFault_xpcproxy-2024-02-03-073430.txt)
[com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151508/com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt)

**Comment by quyenquy2** [comment]
Can you guide me to unjailbeak it?

**Comment by HiSaCC99** [comment]
You can delete /private/preboot/[random numbers]/jb-[some letters] folder to erase the jailbreak environment

**Comment by jthoward64** [comment]
> Can you guide me to unjailbeak it?

#71 #13 #78

**Comment by jthoward64** [comment]
Are there any kernel panic logs?

**Comment by Su4o** [comment]
> Are there any kernel panic logs?

I don't think so.

**Comment by KpwnZ** [comment]
> I was using [Serotonin](https://github.com/mineek/Serotonin) to jailbreak my iPad, but didn’t liked it cause of to many procedures, battery drain problems, etc.) so I switched back to DNAJB (defentlynotajailbreak) and I successfully jailbroke my iPad 6gen (iOS 16.1), but after downloading powercuff, resprining, after ~5 seconds it rebooted my iPad and un-jb’d me. Here are some file logs I got. [JetsamEvent-2024-02-03-072036.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151505/JetsamEvent-2024-02-03-072036.txt) [SystemMemoryReset-2024-02-03-072939.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151506/SystemMemoryReset-2024-02-03-072939.txt) [ExcUserFault_xpcproxy-2024-02-03-073430.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151507/ExcUserFault_xpcproxy-2024-02-03-073430.txt) [com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151508/com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt)

Then just remove powercuff.

**Comment by Su4o** [comment]
> > I was using [Serotonin](https://github.com/mineek/Serotonin) to jailbreak my iPad, but didn’t liked it cause of to many procedures, battery drain problems, etc.) so I switched back to DNAJB (defentlynotajailbreak) and I successfully jailbroke my iPad 6gen (iOS 16.1), but after downloading powercuff, resprining, after ~5 seconds it rebooted my iPad and un-jb’d me. Here are some file logs I got. [JetsamEvent-2024-02-03-072036.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151505/JetsamEvent-2024-02-03-072036.txt) [SystemMemoryReset-2024-02-03-072939.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151506/SystemMemoryReset-2024-02-03-072939.txt) [ExcUserFault_xpcproxy-2024-02-03-073430.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151507/ExcUserFault_xpcproxy-2024-02-03-073430.txt) [com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14151508/com.apple.WebKit.GPU.wakeups_resource-2024-02-03-074129.txt)
> 
> Then just remove powercuff.

Yeah, but i made this issue because it happened multiple times to me. I think it's one of my tweaks so I'll send in my tweak list tmrw.

**Comment by abdolib1** [comment]
random reboot [ ipad pro 2 16.6 ]

**Comment by Su4o** [comment]
Anything seems wrong?

apt:(apt) 2.7.1
base:(base) 1-6
bash:(bash) 5.2.15
ca-certificates:(ca-certificates) 20230909
chariz-keyring:(chariz-keyring) 2021.07.18
coreutils:(coreutils) 9.4
darwintools:(darwintools) 1.6
dash:(dash) 0.5.12
debianutils:(debianutils) 5.7-1
diffutils:(diffutils) 3.9
diskdev-cmds:(diskdev-cmds) 697
dpkg:(dpkg) 1.22.0
dpkg-dev:(dpkg-dev) 1.22.0
ElleKit:(ellekit) 1.0
essential:(essential) 0-5
fakeroot:(fakeroot) 1.31-1
file:(file) 5.43
file-cmds:(file-cmds) 400-1
findutils:(findutils) 4.9.0
gawk:(gawk) 5.1.0-2
gpgv:(gpgv) 2.4.3
grep:(grep) 3.11
gzip:(gzip) 1.13
havoc-keyring:(havoc-keyring) 2022.06.03
KrashKop:(com.foxfort.krashkop) 1.0.2
launchctl:(launchctl) 1:1.1.1
ldid:(ldid) 2.1.5-procursus7
libapt-pkg6.0:(libapt-pkg6.0) 2.7.1
libassuan0:(libassuan0) 2.5.6
libbrotli1:(libbrotli1) 1.1.0
libclang-cpp14:(libclang-cpp14) 14.0.0~5.7.2~RELEASE
libcrypt2:(libcrypt2) 4.4.36
libdimentio0:(libdimentio0) 1:0~20230202.7ffffff
libdpkg-perl:(libdpkg-perl) 1.22.0
libedit0:(libedit0) 3.1-20230828
libffi8:(libffi8) 3.4.4
libgcrypt20:(libgcrypt20) 1.10.2
libgmp10:(libgmp10) 6.3.0
libgnutls30:(libgnutls30) 3.8.1
libgpg-error0:(libgpg-error0) 1.47
libhogweed6:(libhogweed6) 3.9.1
libidn2-0:(libidn2-0) 2.3.4
libintl8:(libintl8) 0.22
libiosexec1:(libiosexec1) 1.3.1
libkrw0:(libkrw0) 1.1.1
libkrw0-xia0o0o0o:(libkrw0-xia0o0o0o) 0.999
libllvm14:(libllvm14) 14.0.0~5.7.2~RELEASE
liblz4-1:(liblz4-1) 1.9.4
liblzma5:(liblzma5) 5.4.4
libmagic1:(libmagic1) 5.43
libmd0:(libmd0) 1.1.0
libmpfr6:(libmpfr6) 4.1.0
libncursesw6:(libncursesw6) 6.4
libnettle8:(libnettle8) 3.9.1
libnpth0:(libnpth0) 1.6-2
libp11-kit0:(libp11-kit0) 0.25.0
libpam-modules:(libpam-modules) 1000.0
libpam2:(libpam2) 20230627
libpcre1:(libpcre1) 8.45-1
libpcre2-8-0:(libpcre2-8-0) 10.42
libplist3:(libplist3) 2.2.0+git20230130.4b50a5a
libpng16-16:(libpng16-16) 1.6.37-2
libreadline8:(libreadline8) 8.2.0-1
libssl-dev:(libssl-dev) 3.0.10
libssl3:(libssl3) 3.0.10
libtapi:(libtapi) 1100.0.11-1
libtasn1-6:(libtasn1-6) 4.19.0
libunistring5:(libunistring5) 1.1
libuuid16:(libuuid16) 1.6.2-3
libxar1:(libxar1) 1.8.0.487.100.1
libxpwn-dev:(libxpwn-dev) 0.5.8+git20220711.c89fba5
libxxhash0:(libxxhash0) 0.8.2
libz-ng2:(libz-ng2) 2.1.3
libzstd1:(libzstd1) 1.5.5
llvm-14:(llvm-14) 14.0.0~5.7.2~RELEASE
llvm-14-dev:(llvm-14-dev) 14.0.0~5.7.2~RELEASE
llvm-14-linker-tools:(llvm-14-linker-tools) 14.0.0~5.7.2~RELEASE
llvm-14-runtime:(llvm-14-runtime) 14.0.0~5.7.2~RELEASE
llvm-dev:(llvm-dev) 14.0.0~5.7.2~RELEASE
login:(login) 14.04.23-1
ncurses-bin:(ncurses-bin) 6.4
ncurses-term:(ncurses-term) 6.4
neofetch:(neofetch) 7.1.0+20220216.ccd5d9f
NewTerm 3 Beta:(ws.hbang.newterm3) 3.0~beta1
odcctools:(odcctools) 973.0.1-1
p7zip:(p7zip) 17.04
perl:(perl) 5.32.1
PowerApp:(com.dave1482.powerapp) 7.0
Powercuff:(com.rpetrich.powercuff) 0.1
PreferenceLoader:(preferenceloader) 2.2.6-1
procursus-keyring:(procursus-keyring) 2020.05.09-4
profile.d:(profile.d) 0-7
sed:(sed) 4.9
shell-cmds:(shell-cmds) 278-2
shshd:(shshd) 1.1.1.1
Sileo:(org.coolstar.sileo) 2.5
snaputil:(snaputil) 12.3
sudo:(sudo) 1.9.14p3
system-cmds:(system-cmds) 950-2
tar:(tar) 1.35
uikittools:(uikittools) 2.1.6-1
unrar:(unrar) 6.2.6
unzip:(unzip) 6.0-28
vi:(vi) 070224
xpwn:(xpwn) 0.5.8+git20220711.c89fba5
xz-utils:(xz-utils) 5.4.4
YTAutoFullScreen:(com.ps.ytautofullscreen) 1.0.3
zip:(zip) 3.0-12
zsh:(zsh) 5.9

**Comment by NoW4U2Kid** [comment]
> Anything seems wrong?
> 
> apt:(apt) 2.7.1 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230909 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 dpkg:(dpkg) 1.22.0 dpkg-dev:(dpkg-dev) 1.22.0 ElleKit:(ellekit) 1.0 essential:(essential) 0-5 fakeroot:(fakeroot) 1.31-1 file:(file) 5.43 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gawk:(gawk) 5.1.0-2 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 gzip:(gzip) 1.13 havoc-keyring:(havoc-keyring) 2022.06.03 KrashKop:(com.foxfort.krashkop) 1.0.2 launchctl:(launchctl) 1:1.1.1 ldid:(ldid) 2.1.5-procursus7 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libclang-cpp14:(libclang-cpp14) 14.0.0~5.7.2~RELEASE libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libdpkg-perl:(libdpkg-perl) 1.22.0 libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw0:(libkrw0) 1.1.1 libkrw0-xia0o0o0o:(libkrw0-xia0o0o0o) 0.999 libllvm14:(libllvm14) 14.0.0~5.7.2~RELEASE liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmagic1:(libmagic1) 5.43 libmd0:(libmd0) 1.1.0 libmpfr6:(libmpfr6) 4.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libplist3:(libplist3) 2.2.0+git20230130.4b50a5a libpng16-16:(libpng16-16) 1.6.37-2 libreadline8:(libreadline8) 8.2.0-1 libssl-dev:(libssl-dev) 3.0.10 libssl3:(libssl3) 3.0.10 libtapi:(libtapi) 1100.0.11-1 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libuuid16:(libuuid16) 1.6.2-3 libxar1:(libxar1) 1.8.0.487.100.1 libxpwn-dev:(libxpwn-dev) 0.5.8+git20220711.c89fba5 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 llvm-14:(llvm-14) 14.0.0~5.7.2~RELEASE llvm-14-dev:(llvm-14-dev) 14.0.0~5.7.2~RELEASE llvm-14-linker-tools:(llvm-14-linker-tools) 14.0.0~5.7.2~RELEASE llvm-14-runtime:(llvm-14-runtime) 14.0.0~5.7.2~RELEASE llvm-dev:(llvm-dev) 14.0.0~5.7.2~RELEASE login:(login) 14.04.23-1 ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 neofetch:(neofetch) 7.1.0+20220216.ccd5d9f NewTerm 3 Beta:(ws.hbang.newterm3) 3.0~beta1 odcctools:(odcctools) 973.0.1-1 p7zip:(p7zip) 17.04 perl:(perl) 5.32.1 PowerApp:(com.dave1482.powerapp) 7.0 Powercuff:(com.rpetrich.powercuff) 0.1 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 unrar:(unrar) 6.2.6 unzip:(unzip) 6.0-28 vi:(vi) 070224 xpwn:(xpwn) 0.5.8+git20220711.c89fba5 xz-utils:(xz-utils) 5.4.4 YTAutoFullScreen:(com.ps.ytautofullscreen) 1.0.3 zip:(zip) 3.0-12 zsh:(zsh) 5.9

Powercuff is confirmed to cause random reboots to some people on rootless jailbreaks btw. I have first hand experience.

**Comment by Su4o** [comment]
> > Anything seems wrong?
> > apt:(apt) 2.7.1 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230909 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 dpkg:(dpkg) 1.22.0 dpkg-dev:(dpkg-dev) 1.22.0 ElleKit:(ellekit) 1.0 essential:(essential) 0-5 fakeroot:(fakeroot) 1.31-1 file:(file) 5.43 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gawk:(gawk) 5.1.0-2 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 gzip:(gzip) 1.13 havoc-keyring:(havoc-keyring) 2022.06.03 KrashKop:(com.foxfort.krashkop) 1.0.2 launchctl:(launchctl) 1:1.1.1 ldid:(ldid) 2.1.5-procursus7 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libclang-cpp14:(libclang-cpp14) 14.0.0~5.7.2~RELEASE libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libdpkg-perl:(libdpkg-perl) 1.22.0 libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw0:(libkrw0) 1.1.1 libkrw0-xia0o0o0o:(libkrw0-xia0o0o0o) 0.999 libllvm14:(libllvm14) 14.0.0~5.7.2~RELEASE liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmagic1:(libmagic1) 5.43 libmd0:(libmd0) 1.1.0 libmpfr6:(libmpfr6) 4.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libplist3:(libplist3) 2.2.0+git20230130.4b50a5a libpng16-16:(libpng16-16) 1.6.37-2 libreadline8:(libreadline8) 8.2.0-1 libssl-dev:(libssl-dev) 3.0.10 libssl3:(libssl3) 3.0.10 libtapi:(libtapi) 1100.0.11-1 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libuuid16:(libuuid16) 1.6.2-3 libxar1:(libxar1) 1.8.0.487.100.1 libxpwn-dev:(libxpwn-dev) 0.5.8+git20220711.c89fba5 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 llvm-14:(llvm-14) 14.0.0~5.7.2~RELEASE llvm-14-dev:(llvm-14-dev) 14.0.0~5.7.2~RELEASE llvm-14-linker-tools:(llvm-14-linker-tools) 14.0.0~5.7.2~RELEASE llvm-14-runtime:(llvm-14-runtime) 14.0.0~5.7.2~RELEASE llvm-dev:(llvm-dev) 14.0.0~5.7.2~RELEASE login:(login) 14.04.23-1 ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 neofetch:(neofetch) 7.1.0+20220216.ccd5d9f NewTerm 3 Beta:(ws.hbang.newterm3) 3.0~beta1 odcctools:(odcctools) 973.0.1-1 p7zip:(p7zip) 17.04 perl:(perl) 5.32.1 PowerApp:(com.dave1482.powerapp) 7.0 Powercuff:(com.rpetrich.powercuff) 0.1 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 unrar:(unrar) 6.2.6 unzip:(unzip) 6.0-28 vi:(vi) 070224 xpwn:(xpwn) 0.5.8+git20220711.c89fba5 xz-utils:(xz-utils) 5.4.4 YTAutoFullScreen:(com.ps.ytautofullscreen) 1.0.3 zip:(zip) 3.0-12 zsh:(zsh) 5.9
> 
> Powercuff is confirmed to cause random reboots to some people on rootless jailbreaks btw. I have first hand experience.

Then what should I do? I normally use powercuff to throttle my ipad. know any alternatives for **amd64**?

**Comment by jthoward64** [comment]
> ipad pro 2

Maybe check on r/jailbreak or the discord

**Comment by NoW4U2Kid** [comment]
> > > Anything seems wrong?
> > > apt:(apt) 2.7.1 base:(base) 1-6 bash:(bash) 5.2.15 ca-certificates:(ca-certificates) 20230909 chariz-keyring:(chariz-keyring) 2021.07.18 coreutils:(coreutils) 9.4 darwintools:(darwintools) 1.6 dash:(dash) 0.5.12 debianutils:(debianutils) 5.7-1 diffutils:(diffutils) 3.9 diskdev-cmds:(diskdev-cmds) 697 dpkg:(dpkg) 1.22.0 dpkg-dev:(dpkg-dev) 1.22.0 ElleKit:(ellekit) 1.0 essential:(essential) 0-5 fakeroot:(fakeroot) 1.31-1 file:(file) 5.43 file-cmds:(file-cmds) 400-1 findutils:(findutils) 4.9.0 gawk:(gawk) 5.1.0-2 gpgv:(gpgv) 2.4.3 grep:(grep) 3.11 gzip:(gzip) 1.13 havoc-keyring:(havoc-keyring) 2022.06.03 KrashKop:(com.foxfort.krashkop) 1.0.2 launchctl:(launchctl) 1:1.1.1 ldid:(ldid) 2.1.5-procursus7 libapt-pkg6.0:(libapt-pkg6.0) 2.7.1 libassuan0:(libassuan0) 2.5.6 libbrotli1:(libbrotli1) 1.1.0 libclang-cpp14:(libclang-cpp14) 14.0.0~5.7.2~RELEASE libcrypt2:(libcrypt2) 4.4.36 libdimentio0:(libdimentio0) 1:0~20230202.7ffffff libdpkg-perl:(libdpkg-perl) 1.22.0 libedit0:(libedit0) 3.1-20230828 libffi8:(libffi8) 3.4.4 libgcrypt20:(libgcrypt20) 1.10.2 libgmp10:(libgmp10) 6.3.0 libgnutls30:(libgnutls30) 3.8.1 libgpg-error0:(libgpg-error0) 1.47 libhogweed6:(libhogweed6) 3.9.1 libidn2-0:(libidn2-0) 2.3.4 libintl8:(libintl8) 0.22 libiosexec1:(libiosexec1) 1.3.1 libkrw0:(libkrw0) 1.1.1 libkrw0-xia0o0o0o:(libkrw0-xia0o0o0o) 0.999 libllvm14:(libllvm14) 14.0.0~5.7.2~RELEASE liblz4-1:(liblz4-1) 1.9.4 liblzma5:(liblzma5) 5.4.4 libmagic1:(libmagic1) 5.43 libmd0:(libmd0) 1.1.0 libmpfr6:(libmpfr6) 4.1.0 libncursesw6:(libncursesw6) 6.4 libnettle8:(libnettle8) 3.9.1 libnpth0:(libnpth0) 1.6-2 libp11-kit0:(libp11-kit0) 0.25.0 libpam-modules:(libpam-modules) 1000.0 libpam2:(libpam2) 20230627 libpcre1:(libpcre1) 8.45-1 libpcre2-8-0:(libpcre2-8-0) 10.42 libplist3:(libplist3) 2.2.0+git20230130.4b50a5a libpng16-16:(libpng16-16) 1.6.37-2 libreadline8:(libreadline8) 8.2.0-1 libssl-dev:(libssl-dev) 3.0.10 libssl3:(libssl3) 3.0.10 libtapi:(libtapi) 1100.0.11-1 libtasn1-6:(libtasn1-6) 4.19.0 libunistring5:(libunistring5) 1.1 libuuid16:(libuuid16) 1.6.2-3 libxar1:(libxar1) 1.8.0.487.100.1 libxpwn-dev:(libxpwn-dev) 0.5.8+git20220711.c89fba5 libxxhash0:(libxxhash0) 0.8.2 libz-ng2:(libz-ng2) 2.1.3 libzstd1:(libzstd1) 1.5.5 llvm-14:(llvm-14) 14.0.0~5.7.2~RELEASE llvm-14-dev:(llvm-14-dev) 14.0.0~5.7.2~RELEASE llvm-14-linker-tools:(llvm-14-linker-tools) 14.0.0~5.7.2~RELEASE llvm-14-runtime:(llvm-14-runtime) 14.0.0~5.7.2~RELEASE llvm-dev:(llvm-dev) 14.0.0~5.7.2~RELEASE login:(login) 14.04.23-1 ncurses-bin:(ncurses-bin) 6.4 ncurses-term:(ncurses-term) 6.4 neofetch:(neofetch) 7.1.0+20220216.ccd5d9f NewTerm 3 Beta:(ws.hbang.newterm3) 3.0~beta1 odcctools:(odcctools) 973.0.1-1 p7zip:(p7zip) 17.04 perl:(perl) 5.32.1 PowerApp:(com.dave1482.powerapp) 7.0 Powercuff:(com.rpetrich.powercuff) 0.1 PreferenceLoader:(preferenceloader) 2.2.6-1 procursus-keyring:(procursus-keyring) 2020.05.09-4 profile.d:(profile.d) 0-7 sed:(sed) 4.9 shell-cmds:(shell-cmds) 278-2 shshd:(shshd) 1.1.1.1 Sileo:(org.coolstar.sileo) 2.5 snaputil:(snaputil) 12.3 sudo:(sudo) 1.9.14p3 system-cmds:(system-cmds) 950-2 tar:(tar) 1.35 uikittools:(uikittools) 2.1.6-1 unrar:(unrar) 6.2.6 unzip:(unzip) 6.0-28 vi:(vi) 070224 xpwn:(xpwn) 0.5.8+git20220711.c89fba5 xz-utils:(xz-utils) 5.4.4 YTAutoFullScreen:(com.ps.ytautofullscreen) 1.0.3 zip:(zip) 3.0-12 zsh:(zsh) 5.9
> > 
> > 
> > Powercuff is confirmed to cause random reboots to some people on rootless jailbreaks btw. I have first hand experience.
> 
> Then what should I do? I normally use powercuff to throttle my ipad. know any alternatives for **amd64**? or anyway to increase battery time on an ios device. (_im not going to replace my battery 0-0_)

You can use either gasolina from https://repo.cypwn.xyz/ or use smartbattery. They both have throttling options.

**Comment by Su4o** [comment]
> > Then what should I do? I normally use powercuff to throttle my ipad. know any alternatives for amd64? or anyway to increase battery time on an ios device. (im not going to replace my battery 0-0)
> 
> Maybe check on r/jailbreak or the discord

tried, but they just said to get a new battery lol

**Comment by nyathea** [comment]
> > > Then what should I do? I normally use powercuff to throttle my ipad. know any alternatives for amd64? or anyway to increase battery time on an ios device. (im not going to replace my battery 0-0)
> 
> > 
> 
> > Maybe check on r/jailbreak or the discord
> 
> 
> 
> tried, but they just said to get a new battery, lol
> 
> 

Maybe thats because you should actually get a new battery instead of just throttling your device which only just makes it slower

**Comment by Su4o** [comment]
> > > > Then what should I do? I normally use powercuff to throttle my ipad. know any alternatives for amd64? or anyway to increase battery time on an ios device. (im not going to replace my battery 0-0)
> > 
> > 
> > > 
> > 
> > 
> > > Maybe check on r/jailbreak or the discord
> > 
> > 
> > tried, but they just said to get a new battery, lol
> 
> Maybe thats because you should actually get a new battery instead of just throttling your device which only just makes it slower

i would, but right now I'm throttling my device. Ill get a new battery like around next year.
