### ISSUE TITLE
On start does something but reboots.

### ISSUE THREAD

**Issue by longsteezy** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#81]
After reboot does something has logs then stays there not moving forward. Something is going on. 
iPhone 14 pro iOS 16.0
![255E4AAC-8E1C-4B4C-A7FF-FEA8AF9F76E2](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/20841584/b6697f5a-f37f-43a3-85aa-ffc27e815d4a)
![B99B5206-6DAB-4A17-A02D-5F152C15D367](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/20841584/7b1904b2-1d07-4fd3-9a52-bee3b3fd84cc)

**Comment by jthoward64** [comment]
#16
