### ISSUE TITLE
1.0.1 New it problem for my ipad pro 12.9 gen 2 ios 16.6 

### ISSUE THREAD

**Issue by trungtoan337** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#83]
[panic-full-2024-02-06-203845.000.zip](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14181006/panic-full-2024-02-06-203845.000.zip)
![IMG_1582](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/115570948/600f86f3-dbe9-4936-aa5b-7cc4ee919482)

**Comment by KpwnZ** [comment]
It's normal if you wipe the jb folder previously.
