### ISSUE TITLE
iPhonex16.4越狱后一切正常，但使用几个小时后，会出现app打不开，白屏的情况，只能重启再次越狱

### ISSUE THREAD

**Issue by abc1593373** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#84]

**Comment by abc1593373** [comment]
iPhonex越狱后一切正常，但使用几个小时后，会出现app打不开，白屏的情况，只能重启再次越狱

**Comment by jthoward64** [comment]
English? Translate has some trouble with your message

**Comment by KpwnZ** [comment]
Duplicate. Try uninstalling some tweaks first.
