### ISSUE TITLE
Random Reboots

### ISSUE THREAD

**Issue by Soteris24** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#87]
My IPad 6th genetation running ios 16.3.1 will randomly reboot while using it. But i have to say the jailbreak and all the tweaks work fine on here :)

**Comment by Su4o** [comment]
> My IPad 6th genetation running ios 16.3.1 will randomly reboot while using it. But i have to say the jailbreak and all the tweaks work fine on here :)

Same thing that happened to me. I’m on IPad 6gen | IOS 16.1, but there’s no fix yet. It’s probably one of your tweaks.

**Comment by Soteris24** [comment]
> > My IPad 6th genetation running ios 16.3.1 will randomly reboot while using it. But i have to say the jailbreak and all the tweaks work fine on here :)
> 
> Same thing that happened to me. I’m on IPad 6gen | IOS 16.1, but there’s no fix yet. It’s probably one of your tweaks.

Oh ok thanks i will see which on it is :)
