### ISSUE TITLE
How jailbreak into safe mode?

### ISSUE THREAD

**Issue by maansial** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#88]
I installed incompatible tweak now every time I rejailbreak I stuk on respiring screen
or some how i can "killall -SEGV SpringBoard" ?

**Comment by jthoward64** [comment]
You'll probably want to use trollstore Filza to wipe your jailbreak, although you could try something more surgical if you're confident

**Comment by HiSaCC99** [comment]
When you click start on the app, hold down the vol+ button. You should enter in Safe Mode.

**Comment by maansial** [comment]
> When you click start on the app, hold down the vol+ button. You should enter in Safe Mode.

on stuck respring screen i just ssh from my ipad to my iphone and able to run this "killall -SEGV SpringBoard" and enter into Safe Mode, delete the tweak Problem Fixed. but thanks for replying <3
