### ISSUE TITLE
Ip8plus sileo missing after sleep

### ISSUE THREAD

**Issue by Haikal016** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#9]
Thanks for dev for making this jailbreak possible i thought jb without checkm8 is ded, most all the thing is working except for missing sileo everytime i sleep my phone.Any chance to provide a proper jailbreak on the future?

**Comment by KpwnZ** [comment]
Weird, we didn't encounter this issue. What about other tweaks or apps? Will they also disappear?

**Comment by Haikal016** [comment]
> Weird, we didn't encounter this issue. What about other tweaks or apps? Will they also disappear?

Cask is working but cannot change from strencth to other.maybe tweak issue?

Other than that,most of the thing is working except the missing sileo.oh yeah im using palerain rootless b4 install ts2 and reboot.maybe the missing sileo has conflicted with trollstore?

**Comment by Haikal016** [comment]
> Weird, we didn't encounter this issue. What about other tweaks or apps? Will they also disappear?

Another issue the jailbreak will automatically reboot my device for no reason

**Comment by KpwnZ** [comment]
> > Weird, we didn't encounter this issue. What about other tweaks or apps? Will they also disappear?
> 
> Cask is working but cannot change from strencth to other.maybe tweak issue?
> 
> Other than that,most of the thing is working except the missing sileo.oh yeah im using palerain rootless b4 install ts2 and reboot.maybe the missing sileo has conflicted with trollstore?

This is related to the injection to pref process and we are aware of that.

**Comment by KpwnZ** [comment]
This was fix in the latest commit a7ac8ac74a2fb809f8029f032e53416dd892bc19.
