### ISSUE TITLE
Opening Sileo whilst Jailbroken causes iPhone to reboot

### ISSUE THREAD

**Issue by Dansco** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#91]
Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:

https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48

Then when I try to Jailbreak again it simply reboots when click Start. Panic log:

https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43

Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.

**Comment by maansial** [comment]
> Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> 
> https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> 
> Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> 
> https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> 
> Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.

i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots

**Comment by Dansco** [comment]
> > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> 
> > 
> 
> > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> 
> > 
> 
> > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> 
> > 
> 
> > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> 
> > 
> 
> > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> 
> 
> 
> i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots 

I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.

**Comment by maansial** [comment]
> > > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> > 
> > 
> > > 
> > 
> > 
> > > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> > 
> > 
> > > 
> > 
> > 
> > > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> > 
> > 
> > > 
> > 
> > 
> > > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> > 
> > 
> > > 
> > 
> > 
> > > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> > 
> > 
> > i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots
> 
> I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.

i just share my personal experience with random reboots <3, it fix my reboots problem every time i open Sileo

**Comment by Dansco** [comment]
> > > > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> 
> > > 
> 
> > > 
> 
> > > i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots
> 
> > 
> 
> > I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.
> 
> 
> 
> i just share my personal experience with random reboots <3, it fix my reboots problem every time i open Sileo 

It's normally how a lot of things get fixed, personal experience sharing. If it fixes it I’m happy. Cheers again.

**Comment by maansial** [comment]
> > > > > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots
> > 
> > 
> > > 
> > 
> > 
> > > I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.
> > 
> > 
> > i just share my personal experience with random reboots <3, it fix my reboots problem every time i open Sileo
> 
> It's normally how a lot of things get fixed, personal experience sharing. If it fixes it I’m happy. Cheers again.

try Zebra ?

**Comment by Dansco** [comment]
I know I’m using Xina on my iPhone 12 iOS 15.3.1 and was told Zebra doesn't work on iOS 15 and above. 
Definitely worth a try though. Thanks.

**Comment by maansial** [comment]
> I know I’m using Xina on my iPhone 12 iOS 15.3.1 and was told Zebra doesn't work on iOS 15 and above.
> Definitely worth a try though. Thanks.
Working fine on 16.3.1

https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/assets/41131282/91c593dd-5cd7-4798-aee7-977d05d9a302

**Comment by Dansco** [comment]
Firstly love the Lock Screen. 
Also definitely installing Zebra then. 🥳

**Comment by kristiantcho** [comment]
> > > > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> > > 
> > > 
> > > i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots
> > 
> > 
> > I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.
> 
> i just share my personal experience with random reboots <3, it fix my reboots problem every time i open Sileo

I have the same issue too, tried using choicy on Sileo and now and then it still causes my device to reboot, also with zebra it’s the same

**Comment by nyathea** [comment]
> > > > > Jailbreak runs fine but sometimes when I open Sileo within seconds my phone reboots. Panic log:
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > https://app.box.com/s/34c949u609ez06tf7sp5yhzg3j1yvg48
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > Then when I try to Jailbreak again it simply reboots when click Start. Panic log:
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > https://app.box.com/s/8purl799r6kaaslk89mahyg9ktccau43
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > Then can't Jailbreak due to reboots. But then if left in stock for a while can Jailbreak fine. Even use Sileo without issue but then open Sileo and reboot.
> 
> > > > 
> 
> > > > 
> 
> > > > i was facing have same problem, just install Choicy then disable tweak injection for Sileo clear cache in Sileo respring and after that never have random reboots
> 
> > > 
> 
> > > 
> 
> > > I have that installed and didn't think to do that with Sileo. Thanks and see how it goes.
> 
> > 
> 
> > i just share my personal experience with random reboots <3, it fix my reboots problem every time i open Sileo
> 
> 
> 
> I have the same issue too, tried using choicy on Sileo and now and then it still causes my device to reboot, also with zebra it’s the same

Switch to dopamine 2.0 its way more stable
