### ISSUE TITLE
Keeps freezing then crashing 

### ISSUE THREAD

**Issue by Nasstyle771** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#92]
Hello! Im on ipad 6th gen ipados16.6.1 and DefinitelyNotAJailbreakTool keeps crashing and rebooting the device (sometimes), leaving the ipad unjailbroken. Is there a way to solve the problem? I have tried at least 60 times and I cant get it to work

**Comment by jthoward64** [comment]
Please send kernel panic or app crash logs

**Comment by Nasstyle771** [comment]
Is it located in app analytics?

**Comment by Nasstyle771** [comment]
Ill send them in a minute

**Comment by Nasstyle771** [comment]
[panic-full-2024-01-31-000651.000.txt](https://github.com/KpwnZ/Def1nit3lyN0tAJa1lbr3akTool/files/14276335/panic-full-2024-01-31-000651.000.txt)

**Comment by Nasstyle771** [comment]
Nevermind it just worked thanks for the help

**Comment by Nasstyle771** [comment]
It worked thanks
