### ISSUE TITLE
uninstall jailbreak

### ISSUE THREAD

**Issue by cristianrb74** [KpwnZ/Def1nit3lyN0tAJa1lbr3akTool#99]
Hello, I'm cristianrb, how can I uninstall this jailbreak since I don't know how to do it without damaging my iPhone, could someone help me, thank you

**Comment by jthoward64** [comment]
You don't really need to unless you need the storage back, see #13 to see how to remove the jailbreak folder

**Comment by KpwnZ** [comment]
Closed as completed.
